application/forms.py
from flask_wtf import FlaskForm
from wtforms import (MultipleFileField, SubmitField,
                     RadioField, IntegerField)
from wtforms_components import ColorField
from wtforms.validators import InputRequired, NumberRange
from wtforms.widgets import NumberInput


class UploadForm(FlaskForm):
    images = MultipleFileField('images')
    submit = SubmitField('UPLOAD')


class ImageSettingsForm(FlaskForm):
    orientation = RadioField('Orientation', default='horizontal',
                             choices=[('horizontal', 'Horizontal Collage'),
                                      ('vertical', 'Vertical Collage')])
    background = ColorField('Background Color', validators=[InputRequired()])
    border = IntegerField(validators=[NumberRange(min=0, max=100)])
    border = IntegerField('Border', widget=NumberInput(min=0, max=100,
                                                       step=1))
    submit = SubmitField('GENERATE COLLAGE')

application/__init__.py
# application/__init__.py

import logging
from os import environ
from flask import Flask
from flask_uploads import configure_uploads, IMAGES, UploadSet
from celery import Celery

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
file_handler = logging.FileHandler('error.log')
formatter = logging.Formatter('%(asctime)s: %(levelname)s: \
                              %(name)s: %(message)s')
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

celery = Celery('tasks', backend='rpc://', broker='pyamqp://guest@127.0.0.1')


def create_app():
    '''Flask application factory'''

    app = Flask(__name__)

    app.config['DEBUG'] = True
    app.config['SECRET_KEY'] = environ.get('SECRET_KEY')
    app.config['UPLOADED_IMAGES_DEST'] = environ.get('UPLOADED_IMAGES_DEST')
    app.config['CELERY_TASK_TRACK_STARTED'] = True
    app.config['CELERY_RESULT_PERSISTENT'] = True
    images = UploadSet('images', IMAGES)
    configure_uploads(app, images)
    celery.conf.update(app.config)

    from application.main.routes import main
    app.register_blueprint(main)

    return app

application/main/routes.py
'''
application/main/routes.py

'''

import ast
import random
import string
import imghdr
from os import environ
from datetime import datetime as dt
from flask import (Blueprint, render_template, request, abort, redirect,
                   jsonify, url_for, flash, session, send_from_directory)
from flask_uploads import IMAGES, UploadSet
from flask_uploads.exceptions import UploadNotAllowed
from application.forms import UploadForm, ImageSettingsForm
from ..tasks import resize_image, merge_images

main = Blueprint('main', __name__,
                 template_folder='templates',
                 static_folder='static')

default_path = environ.get('UPLOADED_IMAGES_DEST')
images = UploadSet('images', IMAGES)


def is_image_valid(image):
    '''Check if image is valid'''

    valid_image = imghdr.what(image)
    return valid_image in ('png', 'jpeg')


def rename_image_file(filename):
    '''Rename files using a random string'''

    extention = filename[-3:]
    chars = ''.join(string.ascii_letters)
    filename = ''.join(random.choice(chars) for _ in range(16))
    return f'{filename}.{extention}'


def check_quantity(files):
    '''Set a limit on the number of files to upload'''

    if len(files) < 2:
        flash('At least 2 images are required.', 'failure')
        return True
    if len(files) > 6:
        flash('Maximum number of images exceeded.', 'failure')
        return True
    return None


def save_image_file(image_file):
    '''Try to save the uploaded image on server'''

    try:
        images.save(image_file)
    except UploadNotAllowed:
        flash('File type not allowed.', 'failure')
        return redirect(url_for('main.index', _external=True))
    return None


@main.get('/')
def index():
    '''Index route'''

    form = UploadForm()
    return render_template('main/index.html', form=form)


@main.post('/')
def uploads():
    '''Display uploaded images'''

    all_files = []
    file_obj = request.files.getlist('images')
    if check_quantity(file_obj):
        return redirect(url_for('main.index', _external=True))
    for img in file_obj:
        if is_image_valid(img) is False:
            flash('Not a valid image file.', 'failure')
            return redirect(url_for('main.index', _external=True))
        img.filename = rename_image_file(img.filename)
        save_image_file(img)
        all_files.append(img.filename)
        session['uploads'] = all_files
    flash('Photos uploaded successfully', 'success')
    return redirect(url_for('main.workspace', _external=True))


@main.route('/queue', methods=['GET', 'POST'])
def get_status():
    '''Get task ID route'''

    task = merge_images.AsyncResult(session['task_id'])

    if task.state == 'PENDING':
        result = {
                'state': task.ready(),
                'status': task.status
                }
    else:
        result = {
                'state': task.ready(),
                'status': task.status
                }
    return jsonify(result)


def set_default_background(background_color):
    '''Set default background to transparent'''

    if background_color == '#000001':
        return (0, 0, 0, 0)
    return background_color


@main.get('/workspace')
def workspace():
    '''Workspace route'''

    form = ImageSettingsForm()
    return render_template('main/workspace.html',
                           form=form, files=session['uploads'])


@main.route('/generate/<images>', methods=['GET', 'POST'])
async def create_collage(images):
    '''Create collage of the images'''

    form = ImageSettingsForm()
    images_list = ast.literal_eval(images)

    if form.validate_on_submit():
        border = int(request.form.get('border'))
        background = set_default_background(request.form.get('background'))
        orientation = request.form.get('orientation')
        all_images = resize_image(images_list, 500, border, background)
        filename = f'collage_{dt.utcnow().strftime("%Y%m%d-%H%M%S.%f")}.png'
        task = merge_images.apply_async(args=[all_images, filename,
                                        orientation], countdown=2)
        session['task_id'] = task.id
        session['collage'] = filename
        return redirect(url_for('main.display_collage', _external=True))
    return render_template('main/workspace.html', form=form)


@main.route('/download/<filename>')
def download_image(filename):
    '''Download collage image'''

    path = environ.get('DOWNLOAD_URL')
    try:
        return send_from_directory(path, session['collage'],
                                   as_attachment=True)
    except FileNotFoundError:
        abort(404)
    return None


@main.get('/result')
def display_collage():
    '''Display collage to download'''

    return render_template('main/result.html', image=session['collage'])


@main.get('/privacy_policy')
def privacy_policy():
    '''Privacy Policy'''

    return render_template('main/privacy_policy.html')


@main.get('/terms_of_service')
def terms_of_service():
    '''Terms Of Service'''

    return render_template('main/terms_of_service.html')


@main.app_errorhandler(404)
def page_not_found(error):
    '''404 Page Not Found'''

    return render_template('404.html'), 404


@main.app_errorhandler(413)
def file_too_large(error):
    '''413 Request Entity Too Large'''

    return render_template('413.html'), 413


@main.app_errorhandler(500)
def internal_server_error(error):
    '''500 Internal Server Error'''

    return render_template('500.html'), 500


@main.app_errorhandler(502)
def bad_gateway_error(error):
    '''502 Bad Gateway Error'''

    return render_template('502.html'), 502

application/templates/413.html
{# application/templates/413.html #}

{% extends "layout.html" %}

{% block title %}Request Entity Too Large{% endblock %}

{% block content %}

  <h1 class="error-text">413 Request Entity Too Large</h1>

  <img class="error-image" src="{{ url_for('static', filename='images/blue_sad_face.png') }}" alt="Sad Face Image">

{% endblock %}

application/templates/502.html
{# application/templates/502.html #}

{% extends "layout.html" %}

{% block title %}502 Bad Gateway Error{% endblock %}

{% block content %}

  <h1 class="error-text">502 Bad Gateway Error</h1>

  <img class="error-image" src="{{ url_for('static', filename='images/blue_sad_face.png') }}" alt="Sad Face Image">

{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="A photo collage tool">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="preload" href="/static/fonts/Arcus-Regular.woff" as="font" type="font/woff" crossorigin> 
    <link rel="stylesheet" media="screen,tv" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{% block title %}{% endblock %} - Photo Collage Tool</title>

  </head>

  <body>
  
    <noscript>
      <div style="color:#FC0000;background-color:#FFFFFF;text-align:center">
        <p>Warning! It seems that JavaScript is not working in your browser. It could be that JavaScript is not supported, or JavaScript is disabled.</p>
        <p>Please enable JavaScript. Some of the features on this website will not function properly with out javascript enabled.</p>
      </div>
    </noscript>
    
    <!-- START header -->

    <header>

      <h1 class="fade-in">Photo Collage Tool</h1>

    </header>

    <!-- END header -->

    <!-- START main -->

    <main class="slide-in-bottom">

      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}

          {% for category, message in messages %}
            <div class="flash-messages {{ category }}">
              <p>{{ message }}</p>
              <span class="close">&#10006;</span>
            </div>
          {% endfor %}

        {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}
  
    </main>

    <!-- END main -->

    <!-- START footer -->

    <footer>

      <img class="wave-image" src="../static/images/wave.svg" alt="wave">

      <p>Created by <a href="https://brandonwallace.cc" target="_blank" rel="nonreferrer">Brandon Wallace</a> &copy; 2021</p>
      <p><a class="login__link" href="{{ url_for('main.terms_of_service') }}">Terms Of Service</a> and
      <a class="login__link" href="{{ url_for('main.privacy_policy') }}">Privacy Policy</a></p>

    </footer>

    <!-- END footer -->

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

  </body>

</html>

application/templates/main/index.html
{# application/templates/main/index.html #}

{% extends "layout.html" %}

{% block title %}Home{% endblock %}

{% block content %}

  <p class="large">Upload Images</p>

  <form class="uploads" enctype="multipart/form-data" method="POST" action="">

    {{ form.csrf_token }}
    {{ form.images(class='browse', multiple='true', id='images') }}
    <p>Hold CTRL to select mutiple files.</p>
    <p>Up to 6 JPG or PNG images, maximum size 5MB.</p>

    <div class="center">

      <div class="spinner">
        <div></div><div></div>
        <div></div><div></div>
        <div></div><div></div>
        <div></div><div></div>
        <div></div><div></div>
        <div></div><div></div>
      </div>

    </div>

    {{ form.submit(class='btn btn--solid upload-btn disabled') }}

  </form>

{% endblock %}

application/templates/main/privacy_policy.html
{# application/templates/main/privacy_policy.html #}

{% extends "layout.html" %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}

  <section>

    <h2 class="center">Privacy Policy</h2>

    <p>Your privacy is important to us. It is Photo Collage Tool's policy to respect your privacy regarding any information we may collect from you across our website, <a href="#"></a>, and other sites we own and operate.</p>
    <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
    <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.</p>
    <p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
    <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
    <p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
    <p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
    <p>This policy is effective as of 01 June 2021.</p>

  </section>

{% endblock %}

application/templates/main/result.html
{# application/templates/main/result.html #}

{% extends "layout.html" %}

{% block title %}Result{% endblock %}

{% block content %}

  <div class="collage">

    <img class="collage__image" src="../static/images/uploads/{{ image }}" alt="Collage Image Loading...">

  </div>

  <div class="center">

    <div class="spinner">
      <div></div><div></div>
      <div></div><div></div>
      <div></div><div></div>
      <div></div><div></div>
      <div></div><div></div>
      <div></div><div></div>
    </div>

  </div>
  
  <a class="btn download-btn" href="{{ url_for('main.download_image', filename=image) }}">DOWNLOAD</a>

  <a class="btn new-collage-btn" href="{{ url_for('main.index') }}">NEW COLLAGE</a>

  <script src="{{ url_for('static', filename='js/loadimage.js') }}"></script>

{% endblock %}

application/templates/main/terms_of_service.html
{# application/templates/main/terms_of_service.html #}

{% extends "layout.html" %}

{% block title %}Terms of Service{% endblock %}

{% block content %}

  <section>

    <h2 class="center">Terms of Service</h2>

    <h3>1. Terms</h3>

    <p>By accessing the website at <a href="https://photocollagetool.art"></a>, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.</p>
    <h3>2. Use License</h3>

    <ol type="a">
       <li>Permission is granted to temporarily download one copy of the materials (information or software) on Photo Collage Tool's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
       <ol type="i">
           <li>modify or copy the materials;</li>
           <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
           <li>attempt to decompile or reverse engineer any software contained on Photo Collage Tool's website;</li>
           <li>remove any copyright or other proprietary notations from the materials; or</li>
           <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
       </ol>
        </li>
       <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by Photo Collage Tool at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.</li>
    </ol>
    <h3>3. Disclaimer</h3>

    <ol type="a">
       <li>The materials on Photo Collage Tool's website are provided on an 'as is' basis. Photo Collage Tool makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</li>
       <li>Further, Photo Collage Tool does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</li>

      <li>You may not upload, post or transmit any Content that:</li>
        <ul>
          <li>Infringes any third party’s copyrights or other intellectual property rights, contract rights or any other rights of any person;
          <li>Contains any pornographic, racist, defamatory, libelous or otherwise immoral, vulgar or obscene content;
          <li>Depicts unlawful or violent, hateful or threatening or otherwise inappropriate acts;
          <li>Offends, defames, harasses or otherwise damages Photo Collage Tool or any third party;
          <li>Violates any law, statute, or regulation.
        </ul>
    </ol>
    
    <h3>4. Limitations</h3>

    <p>In no event shall Photo Collage Tool or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Photo Collage Tool's website, even if Photo Collage Tool or a Photo Collage Tool authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
    <h3>5. Accuracy of materials</h3>

    <p>The materials appearing on Photo Collage Tool's website could include technical, typographical, or photographic errors. Photo Collage Tool does not warrant that any of the materials on its website are accurate, complete or current. Photo Collage Tool may make changes to the materials contained on its website at any time without notice. However Photo Collage Tool does not make any commitment to update the materials.</p>
    <h3>6. Links</h3>

    <p>Photo Collage Tool has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Photo Collage Tool of the site. Use of any such linked website is at the user's own risk.</p>
    <h3>7. Modifications</h3>

    <p>Photo Collage Tool may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>
    <h3>8. Governing Law</h3>
    <p>These terms and conditions are governed by and construed in accordance with the laws of New York and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>

  </section>

{% endblock %}

application/templates/main/workspace.html
{# application/templates/main/workspace.html #}

{% extends "layout.html" %}

{% block title %}Workspace{% endblock %}

{% block content %}

  <p class="large">Uploaded images</p>

  <div class="thumbnails">

    {% if files %}
      {% for file in files %}

        <img class="thumbnail__images" src="static/images/uploads/{{ file }}" alt="PNG Image">

      {% endfor %}
    {% endif %}

  </div>

  <div id="status"></div>

  <form action="{{ url_for('main.create_collage', images=files) }}" method="POST">
  
    {{ form.csrf_token }}

    <div class="options">

      <ul>

        {% for subfield in form.orientation %}
          <li>
            <span>{{ subfield }}</span>
            <span>{{ subfield.label }}</span>
          </li>
        {% endfor %}

        <li>
          {{ form.background(value="#000001") }}
          {{ form.background.label }}
        </li>
        <li>
          {{ form.border(value="0") }}
          {{ form.border.label }}
        </li>

      </ul>

      {{ form.submit(class_='btn generate-btn') }}

    </div>

  </form>

{% endblock %}

application/templates/maintenance.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="A photo collage tool">
    <link rel="shortcut icon" href="static/images/favicon.ico">
    <title>Maintenance - Photo Collage Tool</title>

    <style>

      @font-face {
      font-family: "Arcus-Regular";
      src: url("static/fonts/Arcus-Regular.eot?") format("eot"),
          url("static/fonts/Arcus-Regular.woff") format("woff"),
          url("static/fonts/Arcus-Regular.ttf") format("truetype"),
          url("static/fonts/Arcus-Regular.svg#Arcus") format("svg");
          font-weight: normal;
          font-style: normal;
      }
      html,
      body {
	      margin: 0;
	      padding: 0;
	      width: 100%;
	      height: 100%;
	      font-size: 100%;
      }
      body {
          margin: 0;
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          font-weight: 400;
          line-height: 1.75;
          min-height: 100vh;
          background: #FFE970;
          -webkit-box-orient: vertical;
          -webkit-box-direction: normal;
          -ms-flex-direction: column;
          flex-direction: column;
          font-family: "Arcus-Regular", monospace;
      }
      header {
	      margin-bottom: 2em;
      }
      main {
  	      width: 100%;
  	      padding: .5em;
  	      margin: 0 auto;
  	      display: block;
  	      -webkit-box-sizing: border-box;
  	      box-sizing: border-box;
      }
      header h1 {
        	color: #FFFFFF;
        	font-size: 3rem;
        	margin: 1rem 0 0 0;
        	text-align: center;
        	-webkit-transform: scale(1) rotate(-5deg) translateX(-13px) translateY(0) skewX(-5deg) skewY(-1deg);
        	-ms-transform: scale(1) rotate(-5deg) translateX(-13px) translateY(0) skewX(-5deg) skewY(-1deg);
        	transform: scale(1) rotate(-5deg) translateX(-13px) translateY(0) skewX(-5deg) skewY(-1deg);
        	text-shadow: 1.25px 1.25px 0 #003A93,
                      -1.25px -1.25px 0 #003A93,
                      -1.25px 1.25px 0 #003A93,
                      1.25px -1.25px 0 #003A93,
                      1px 1px #0050EE,
                      2px 2px #0050EE,
                      3px 3px #0050EE,
                      4px 4px #0050EE,
                      5px 5px #0050EE,
                      6px 6px #0050EE,
                      7px 7px #0050EE,
                      8px 8px #0050EE,
                      9px 9px #0050EE,
                      10px 10px #0050EE,
                      11px 11px #0050EE,
                      12px 12px #0050EE,
                      13px 13px #0050EE,
                      14px 14px #0050EE,
                      15px 15px #0050EE,
                      16px 16px #0050EE,
                      17px 17px #0050EE,
                      18px 18px #0050EE,
                      19px 19px #0050EE,
                      20px 20px #0050EE,
                      21px 21px #0050EE,
                      22px 22px #0050EE,
                      23px 23px #0050EE,
                      24px 24px #0050EE,
                      25px 25px #0050EE,
                      27px 27px 6px #000000;
      }
      .error {
        	max-width: 900px;
        	margin: 0 auto;
      }
      .error__text {
        	color: #022A73;
        	text-align: center;
        	font-size: 2rem;
      }
      .error__img {
        	display: block;
        	margin: 0 auto 8em auto;
        	max-width: 280px;
      }
      footer {
    	  height: 200px;
    	  margin-top: auto;
    	  position: relative;
    	  text-align: center;
    	  display: flex;
    	  flex-direction: column;
    	  align-items: center;
    	  justify-content: center;
    	  background-color: #0050CC;
      }
      footer p,
      footer p a {
          color: #FFFFFF;
          margin-bottom: 0;
      }
      .wave-image {
    	  left: 0;
    	  right: 0;
    	  width: 100%;
    	  max-height: 170px;
    	  bottom: 200px;
    	  position: absolute;
      }
      @media only screen and (min-width: 800px) {
            .error__text {
            	font-size: 3.052rem;
            }
        }

    </style>

  </head>

  <body>

    <!-- START header -->

    <header>

      <h1>Photo Collage Tool</h1>

    </header>

    <!-- END header -->

    <!-- START main -->

    <main>

      <div class="error">

        <h2 class="error__text">Sorry, Photocollagetool.art is temporarily down for scheduled maintenance.</h2>
        <img class="error__img" src="static/images/blue_sad_face.png" alt="Unhappy face PNG image">

      </div>

    </main>

    <!-- END main -->

    <!-- START footer -->

    <footer>

      <img class="wave-image" src="static/images/wave.svg" alt="wave">

      <p>Created by <a href="https://brandonwallace.cc" target="_blank" rel="nonreferrer">Brandon Wallace</a> &copy; <script>document.write(new Date().getFullYear());</script></p>
      <p><a class="login__link" href="templates/main/terms_of_service.html">Terms Of Service</a> and
      <a class="login__link" href="templates/main/privacy_policy.html">Privacy Policy</a></p>

    </footer>

    <!-- END footer -->

  </body>

</html>